language: python
sudo: false
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
    env: TEST_TYPE=prcheck HYPOTHESIS_PROFILE=ci
  - python: '3.6'
    env: TEST_TYPE=prcheck HYPOTHESIS_PROFILE=ci
  - python: '2.7'
    env: TEST_TYPE=prcheck-py2 HYPOTHESIS_PROFILE=ci
install:
- pip install -r requirements-dev.txt -r requirements-docs.txt
- pip install -e .
- pip install -e ".[event-file-poller]"
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
