language: python
env:
  global:
  - INSTALL_STRING=".[event-file-poller]" TEST_TYPE=prcheck HYPOTHESIS_PROFILE=ci
jobs:
  include:
  - python: '3.8'
    dist: xenial
    env: INSTALL_STRING="."
  - python: '3.8'
    dist: xenial
  - python: '3.7'
    dist: xenial
  - python: '3.6'
  - python: '2.7'
    env: TEST_TYPE=prcheck-py2
install:
- pip install -r requirements-dev.txt -r requirements-docs.txt
- pip install -e "$INSTALL_STRING"
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
