language: python
sudo: false
env: HYPOTHESIS_PROFILE=ci
matrix:
  include:
  - python: '3.6'
    env: TEST_TYPE=prcheck
  - python: '2.7'
    env: TEST_TYPE=prcheck-py2
install:
- pip install -r requirements-dev.txt -r requirements-docs.txt
- pip install -e .
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
